domain_path: C:\Users\Sergiu\Desktop\Vitis\Platforma_SSC\export\Platforma_SSC\sw\standalone_ps7_cortexa9_0
app_src_dir: C:\Xilinx\Vitis\2024.1\data\embeddedsw\lib\sw_apps\hello_world
template: hello_world
